### ISSUE TITLE
Validation fails when attribute has .to_array_type

### ISSUE THREAD

**Issue by majksner** [DmitryTsepelev/store_model#11]
Hi @DmitryTsepelev 

I think I've found one more issue.

After updating to 0.3.1 and trying to save model with attribute .to_array_type 

```ruby
NoMethodError - undefined method `invalid?' for #<Array:0x00007f97219194d8>:
```

from https://github.com/DmitryTsepelev/store_model/blob/ac094e4b7b187c7bd0f494022f8fd600a7cabcde/lib/active_model/validations/store_model_validator.rb#L12

After adding:

```ruby
elsif value.respond_to?(:invalid) && value.invalid?
```
 (`value` is `Array`)

Seems to be fine. 

Let me know if you need more info.

Thanks!

**Comment by DmitryTsepelev** [comment]
Thanks! I've released 0.3.2 with a [fix](https://github.com/DmitryTsepelev/store_model/pull/12) - now when validating array it marks object invalid when at least one array member is invalid. Let me know if it resolves the issue

**Comment by majksner** [comment]
I'll try it tomorrow and let you know.

**Comment by majksner** [comment]
I can confirm it works, thanks!
