### ISSUE TITLE
NoMethodError serialize_unknown_attributes? on upgrading to 3.0.0

### ISSUE THREAD

**Issue by phinze** [DmitryTsepelev/store_model#174]
When upgrading to 3.0.0, I see a lot of test failures on a model with an enum:

```
NoMethodError: undefined method `serialize_unknown_attributes?' for nil:NilClass
```

I believe #173 will fix it, but I figured it was worth making a quick issue to track the problem too.

**Comment by bf4** [comment]
Thanks @phinze for making this issue.  Came here to see if there was anything after I couldn't see anything obvious in the changelog or diff.

**Comment by bf4** [comment]
Happened to get my head in the space and found the fix https://github.com/DmitryTsepelev/store_model/pull/176 Not sure about the test. Having trouble getting all tests to pass, but my new test passes 🤷

**Comment by DmitryTsepelev** [comment]
Thank you all for help! The first PR is merged and I'm gonna to merge a second one right now. Please reach out if something is off 🙂
